-- Demo preview user — must exist before the owner-scoped rows below FK auth.users(id).
-- password: rapidnative-demo (editor preview only — real GoTrue cannot verify this hash)
insert into auth.users (id, email, encrypted_password, email_confirmed_at)
values ('00000000-0000-0000-0000-000000000001', 'demo@rapidnative.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now())
on conflict (id) do update
  set email = excluded.email,
      encrypted_password = excluded.encrypted_password,
      email_confirmed_at = excluded.email_confirmed_at;

-- Demo profile with an ACTIVE account so the app gate lets the signed-in preview user through.
-- The real Hagana ID is generated by the database BEFORE INSERT trigger (never client-side).
insert into profiles (id, full_name, phone, account_status) values
  ('00000000-0000-0000-0000-000000000001', 'Demo User', '+211123456789', 'active')
on conflict (id) do nothing;

-- Real recipient profiles for the Send Money search. OTHER real users so the demo
-- user can search for, and is prevented from selecting, themselves.
insert into auth.users (id, email, encrypted_password, email_confirmed_at)
values
  ('00000000-0000-0000-0000-000000000002', 'achol@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now()),
  ('00000000-0000-0000-0000-000000000003', 'kuol@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now()),
  ('00000000-0000-0000-0000-000000000004', 'lado@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now()),
  ('00000000-0000-0000-0000-000000000005', 'rebecca@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now()),
  -- System commission accounts the send_money RPC credits the 50/50 fee split to.
  -- MTN commission wallet owner:
  ('00000000-0000-0000-0000-0000000000a1', 'mtn.commission@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now()),
  -- Hagana Pay platform commission wallet owner:
  ('00000000-0000-0000-0000-0000000000a2', 'hagana.commission@hagana.com', 'pbkdf2$100000$52617069644e61746976652044656d6f$ebd41bf86ab4f47040854a1e4968e2fdc414e15db6a4397f3271e1b1d56b2061', now())
on conflict (id) do nothing;

insert into profiles (id, full_name, phone, account_status) values
  ('00000000-0000-0000-0000-000000000002', 'Achol Nyok', '+211700000002', 'active'),
  ('00000000-0000-0000-0000-000000000003', 'Kuol Mayen', '+211700000003', 'active'),
  ('00000000-0000-0000-0000-000000000004', 'Lado Wani', '+211700000004', 'active'),
  ('00000000-0000-0000-0000-000000000005', 'Rebecca Jok', '+211700000005', 'active')
on conflict (id) do nothing;

insert into transactions (id, user_id, title, type, amount, created_at) values
  ('txn-1', '00000000-0000-0000-0000-000000000001', 'Deposit', 'deposit', 100000, now() - interval '2 hours'),
  ('txn-2', '00000000-0000-0000-0000-000000000001', 'Merchant Payment', 'merchant_payment', -25000, now() - interval '5 hours'),
  ('txn-3', '00000000-0000-0000-0000-000000000001', 'Loan Repayment', 'loan_repayment', -50000, now() - interval '1 day 3 hours'),
  ('txn-4', '00000000-0000-0000-0000-000000000001', 'Transfer Received', 'transfer_received', 200000, now() - interval '1 day 7 hours'),
  ('txn-5', '00000000-0000-0000-0000-000000000001', 'Withdrawal', 'withdrawal', -30000, now() - interval '2 days 4 hours'),
  ('txn-6', '00000000-0000-0000-0000-000000000001', 'Transfer Sent', 'transfer_sent', -15000, now() - interval '3 days 6 hours');

-- SSP wallets for the demo preview user, the recipient profiles, AND the two system
-- commission accounts. The demo user gets a funded balance so the real send_money RPC
-- can be exercised end-to-end in preview. Commission wallets start at 0 and only accrue
-- once a real transfer executes. No fake ledger rows are created here.
insert into wallets (id, user_id, currency, balance) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'SSP', 1250000.00),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000002', 'SSP', 500000.00),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000003', 'SSP', 300000.00),
  ('00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000004', 'SSP', 750000.00),
  ('00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000005', 'SSP', 900000.00),
  -- MTN commission wallet (50% of fee):
  ('00000000-0000-0000-0000-0000000000a1', '00000000-0000-0000-0000-0000000000a1', 'SSP', 0),
  -- Hagana Pay commission wallet (50% of fee):
  ('00000000-0000-0000-0000-0000000000a2', '00000000-0000-0000-0000-0000000000a2', 'SSP', 0)
on conflict (user_id, currency) do nothing;
