import { useState } from 'react';
import {
  Text,
  View,
  ScrollView,
  Pressable,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeftIcon, RefreshCwIcon } from 'lucide-react-native';
import { cssInterop } from 'nativewind';
import { PrimaryButton, InputField } from '@/components/ui';
import { HaganaLogo } from '@/components';
import { useAuth } from '@/src/hooks';
import { useApp } from '@/src/providers/AppProvider';

cssInterop(ArrowLeftIcon, { className: { target: 'style', nativeStyleToProp: { color: true } } });
cssInterop(RefreshCwIcon, { className: { target: 'style', nativeStyleToProp: { color: true } } });

const RESEND_COOLDOWN_SECONDS = 30;

export default function VerificationScreen() {
  const { client } = useApp();
  const { verifyOtp, resendOtp } = useAuth();
  const params = useLocalSearchParams<{ phone?: string; full_name?: string }>();

  // The phone used during signup (source of truth for OTP verification). We never accept a
  // user id from the route — the authenticated id comes from the Session returned by Supabase
  // after a successful OTP verification.
  const signupPhone = params.phone?.trim() ?? '';
  const fullName = params.full_name?.trim() ?? '';

  const [code, setCode] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [resendCountdown, setResendCountdown] = useState(0);
  const [resendLoading, setResendLoading] = useState(false);

  const handleVerify = async () => {
    setError(null);
    const otp = code.trim();
    if (otp.length !== 6 || !/^[0-9]{6}$/.test(otp)) {
      setError('Please enter the 6-digit code we sent you.');
      return;
    }
    try {
      // 1. Verify the OTP against the signup phone using Supabase Auth. No success unless
      //    Supabase confirms it. On success Supabase returns the authenticated session.
      const data = await verifyOtp.mutateAsync({ phone: signupPhone, token: otp });
      const userId = data?.user?.id ?? data?.session?.user?.id;
      if (!userId) {
        throw new Error('Your number was not verified. Please try again.');
      }

      // 2. Create the profile only after successful verification, keyed to the authenticated
      //    user id from Supabase. The real Hagana ID is generated by the database on insert
      //    (never supplied by the client). account_status is pending_pin — NOT into the app yet.
      const { error: profileError } = await client.from('profiles').upsert(
        {
          id: userId,
          full_name: fullName,
          phone: signupPhone,
          account_status: 'pending_pin',
        },
        { onConflict: 'id' },
      );
      if (profileError) throw profileError;

      // 3. Profile created — send the user to set their PIN (not the dashboard).
      router.replace(`/(auth)/create-pin?full_name=${encodeURIComponent(fullName)}&phone=${encodeURIComponent(signupPhone)}`);
    } catch (err: any) {
      const message = err?.message ?? 'Something went wrong. Please try again.';
      if (/expired|has expired/i.test(message)) {
        setError('This code has expired. Tap Resend Code to get a new one.');
      } else if (/invalid|incorrect|token/i.test(message)) {
        setError('That code is incorrect. Please check it and try again.');
      } else if (/network|fetch|connection/i.test(message)) {
        setError('Network error. Please check your connection and try again.');
      } else {
        setError(message);
      }
    }
  };

  const handleResend = async () => {
    if (resendCountdown > 0) return; // prevent rapid repeated requests
    setError(null);
    setResendLoading(true);
    try {
      await resendOtp.mutateAsync({ phone: signupPhone });
      setResendCountdown(RESEND_COOLDOWN_SECONDS);
      const timer = setInterval(() => {
        setResendCountdown((c) => {
          if (c <= 1) {
            clearInterval(timer);
            return 0;
          }
          return c - 1;
        });
      }, 1000);
    } catch (err: any) {
      const message = err?.message ?? '';
      if (/network|fetch|connection/i.test(message)) {
        setError('Network error. Please check your connection and try again.');
      } else {
        setError('We could not resend the code. Please try again shortly.');
      }
    } finally {
      setResendLoading(false);
    }
  };

  return (
    <SafeAreaView edges={['top']} className="flex-1 bg-background">
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={{ flex: 1 }}
      >
        <ScrollView
          contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 40 }}
          keyboardShouldPersistTaps="handled"
        >
          {/* Header */}
          <Pressable
            onPress={() => router.back()}
            hitSlop={10}
            className="mt-3 w-11 h-11 rounded-full bg-card border border-border items-center justify-center"
          >
            <ArrowLeftIcon size={20} className="text-foreground" />
          </Pressable>

          {/* Logo */}
          <View className="items-center mt-4 mb-6">
            <HaganaLogo width={170} height={80} />
          </View>

          {/* Title */}
          <View className="mt-2">
            <Text className="text-3xl font-black tracking-tight text-foreground">Verify your number</Text>
            <Text className="mt-1.5 text-base text-muted-foreground leading-5">
              Enter the one-time code we sent to{' '}
              <Text className="font-bold text-foreground">{signupPhone || 'your mobile number'}</Text>.
            </Text>
          </View>

          {/* Form */}
          <View className="mt-7 gap-4">
            <InputField
              label="Mobile Number"
              placeholder="+211 12 345 6789"
              value={signupPhone}
              onChangeText={() => {}}
              keyboardType="phone-pad"
              editable={false}
            />
            <InputField
              label="Verification Code"
              placeholder="6-digit code"
              value={code}
              onChangeText={(t) => setCode(t.replace(/[^0-9]/g, '').slice(0, 6))}
              keyboardType="numeric"
            />
          </View>

          {error ? (
            <Text className="mt-3 text-xs text-destructive">{error}</Text>
          ) : null}

          {/* Resend */}
          <Pressable
            onPress={handleResend}
            disabled={resendCountdown > 0 || resendLoading}
            className="mt-5 flex-row items-center justify-center gap-2"
          >
            {resendLoading ? (
              <ActivityIndicator size="small" color="#0d5c2e" />
            ) : (
              <RefreshCwIcon size={16} className="text-primary" />
            )}
            <Text className="text-sm font-semibold text-primary">
              {resendCountdown > 0
                ? `Resend code in ${resendCountdown}s`
                : resendLoading
                  ? 'Resending…'
                  : 'Resend Code'}
            </Text>
          </Pressable>

          {/* Submit */}
          <View className="mt-8">
            <PrimaryButton
              title={verifyOtp.isPending ? 'Verifying…' : 'Verify & Continue'}
              onPress={handleVerify}
              loading={verifyOtp.isPending}
              disabled={verifyOtp.isPending}
            />
          </View>

          <Text className="mt-5 text-center text-[11px] text-muted-foreground">
            We never store your code. It is verified directly with the network.
          </Text>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
